name: Publish anonymized snapshot to repo2

on:
  push:
    branches: ["main"]   # set as needed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source (no persisted creds)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Stage files for snapshot
        run: |
          rm -rf _snapshot
          mkdir -p _snapshot
          # Copy the *files you want* in repo2. Add/remove excludes as needed.
          #  --exclude ".git" \
          #  --exclude ".github" \
          rsync -a \
            --delete \
            --exclude "node_modules" \
            ./ _snapshot/

      - name: Create one commit with generic identity
        working-directory: _snapshot
        run: |
          git init
          git checkout main
          git config user.name  "Sync Bot"
          git config user.email "sync@example.invalid"
          git add -A
          git commit -m "update"  # <-- no source details

      - name: Push snapshot to repo2 (overwrite)
        env:
          REPO2_URL:   https://github.com/Rabasa2025/public-app-node.git
          REPO2_TOKEN: ${{ vars.REPO2_TOKEN }}
        run: |
          set -e
          AUTH="$(printf "x-access-token:${REPO2_TOKEN}" | base64 -w0 2>/dev/null || printf "x-access-token:${REPO2_TOKEN}" | base64)"
          git -C _snapshot \
            -c "http.${REPO2_URL}.extraheader=Authorization: Basic ${AUTH}" \
            push --force "${REPO2_URL}" main:main
