name: Publish anonymized history to repo2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  anonymize-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install git-filter-repo
        run: |
          python3 -m pip install --user git-filter-repo
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Rewrite authors/committers/messages
        run: |
          git config user.name  "Temp Runner"
          git config user.email "runner@example.invalid"

          git filter-repo --force \
            --commit-callback 'c.author_name = b"Sync Bot" c.author_email = b"sync@example.invalid" c.committer_name = b"Sync Bot" c.committer_email = b"sync@example.invalid" c.message = b"update\n"'

      - name: Push rewritten history to repo2 (force)
        env:
          REPO2_URL:   https://github.com/Rabasa2025/public-app-node.git
          REPO2_TOKEN: ${{ vars.REPO2_TOKEN }}
        run: |
          set -e
          AUTH="$(printf "x-access-token:${REPO2_TOKEN}" | base64 -w0 2>/dev/null || printf "x-access-token:${REPO2_TOKEN}" | base64)"
          git -c "http.${REPO2_URL}.extraheader=Authorization: Basic ${AUTH}" \
              push --force "${REPO2_URL}" main:main
